apiVersion: v2
name: calyptia-standalone
description: Umbrella chart to configure a Calyptia Core control plane and supporting on-premise appliance.
home: https://calyptia.com/products/calyptia-core/
icon: https://storage.googleapis.com/calyptia_public_resources_bucket/logo-darkmode.svg
type: application
version: 2.0.1
appVersion: "v1.6.5"
maintainers:
  - name: Calyptia
    email: hello@calyptia.com
    url: www.calyptia.com
dependencies:
  # Core Operator chart
  - name: core-operator
    version: 2.x.x
    repository: https://helm.calyptia.com
    condition: operator.enabled
  - name: core-crd
    version: 2.x.x
    repository: https://helm.calyptia.com
    condition: operator.enabled
  # Useful helpers: https://github.com/bitnami/charts/tree/main/bitnami/common
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: common
  - name: loki-stack
    repository: https://grafana.github.io/helm-charts
    version: 2.9.10
    alias: loki-stack
    condition: monitoring.grafana
  # Cannot use the chart due to incompatible usage of global.imagePullSecrets
  # Instead we embed it
  # - name: reloader
  #   version: 1.x.x
  #   repository: https://stakater.github.io/stakater-charts
  #   alias: reloader
  #   condition: reloader.enabled
  # Use the OSS Fluent Bit chart for monitoring
  - name: fluent-bit
    version: 0.x.x
    repository: https://fluent.github.io/helm-charts
    condition: monitoring.fluentBit
    alias: monitoring-daemonset
  - name: fluent-bit
    version: 0.x.x
    repository: https://fluent.github.io/helm-charts
    condition: monitoring.fluentBit
    alias: monitoring-aggregator
