apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calyptia-core-chart.fullname" . }}
  labels:
    {{- include "calyptia-core-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calyptia-core-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calyptia-core-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calyptia-core-chart.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - -debug=true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CORE_INSTANCE_TAGS
              value: {{ .Values.core_instance_tags }}
            - name: CORE_INSTANCE_ENVIRONMENT
              value: {{ .Values.core_instance_environment | default "default" }}
            - name: CORE_INSTANCE_CLUSTER_LOGGING
              value: "{{ .Values.cluster_logging | default "false" }}"
            - name: AGGREGATOR_NAME
              value: {{ .Values.name }}
            - name: PROJECT_TOKEN
              value: {{ required "A valid Calyptia project_token is required." .Values.project_token }}
            - name: AGGREGATOR_FLUENTBIT_CLOUD_URL
              value: {{ .Values.api_url | default "https://cloud-api.calyptia.com/" }}
            - name: AGGREGATOR_FLUENTBIT_TLS_VERIFY
              value: "{{ .Values.tls_verify | default "on" }}"
            - name: AGGREGATOR_FLUENTBIT_TLS
              value: "{{ .Values.tls | default "on" }}"
            - name: AGGREGATOR_SIDECAR_URL
              value: "{{ .Values.sidecar_url }}"
            - name: CORE_INSTANCE_SERVICE_ACCOUNT_NAME
              value: "{{ include "calyptia-core-chart.serviceAccountName" . }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
