apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calyptia-core-chart.fullname" . }}
  labels:
    {{- include "calyptia-core-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calyptia-core-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calyptia-core-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calyptia-core-chart.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - -debug=true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CORE_INSTANCE_TAGS
              value: {{ .Values.coreInstance.tags }}
            - name: CORE_INSTANCE_ENVIRONMENT
              value: {{ default "default" .Values.coreInstance.environment }}
            - name: CORE_INSTANCE_CLUSTER_LOGGING
              value: {{ default false .Values.coreInstance.clusterLogging | quote }}
            - name: AGGREGATOR_NAME
              value: {{ .Values.name }}
            - name: PROJECT_TOKEN
              value: {{ required "A valid Calyptia coreInstance.projectToken is required." .Values.coreInstance.projectToken }}
            - name: AGGREGATOR_FLUENTBIT_CLOUD_URL
              value: {{ default "https://cloud-api.calyptia.com/" .Values.coreInstance.apiUrl }}
            - name: AGGREGATOR_FLUENTBIT_TLS_VERIFY
              value: {{ default true .Values.coreInstance.tlsVerify | quote }}
            - name: AGGREGATOR_FLUENTBIT_TLS
              value: {{ default true .Values.coreInstance.tls | quote }}
            - name: CORE_INSTANCE_SERVICE_ACCOUNT_NAME
              value: {{ include "calyptia-core-chart.serviceAccountName" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
