# Default values for calyptia-core-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

machine_id: ""

# core instance unique name.
name: ""
project_token: ""
api_url: "https://cloud-api.calyptia.com/"
sidecar_url: "nats://tcp-4222-nats-messaging.default.svc.local:4222"

# core instance variables required at creation/register time on the Calyptia Cloud API.
core_instance_environment: "default"
# comma separated set of tags used when creating the core_instance on the Calyptia Cloud API.
# Please note that --set-string doesn't parses comma delimited values properly
# and requires to escape the strings as in (tag\,tag2).
# TODO: look for an array value.
core_instance_tags: ""
# Experimental: enable of disable the cluster logging functionality for this core instance.
cluster_logging: false

image:
  repository: ghcr.io/calyptia/core
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service: {}
ingress: {}
resources: {}
autoscaling: {}
nodeSelector: {}
tolerations: []
affinity: {}

# OpenShift-specific configuration
openShift:
  enabled: false
  securityContextConstraints:
    create: true
    name: ""
    annotations: {}
    # Use existing SCC in cluster, rather then create new one
    existingName: ""
