{{- if and (.Values.cloudApi.enabled) (.Values.cloudApi.postgres.enabled) -}}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  name: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
