{{- if .Values.cloudApi.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cloud-api
  name: cloud-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ default "LoadBalancer" .Values.cloudApi.service.type }}
  ports:
    - name: "cloud-api"
      port: {{ default 5000 .Values.cloudApi.service.port }}
      targetPort: 5000
  selector: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cloud-api
{{- end }}
