{{- if .Values.cloudApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "cloud.serviceAccountName" . }}
  {{- $mergedAnnotations := merge .Values.cloudApi.serviceAccount.annotations .Values.commonAnnotations }}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $mergedAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
