{{- if .Values.cloudApi.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/name: cloud
    app.kubernetes.io/instance: calyptia
  labels:
    app.kubernetes.io/component: postgres
  name: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
