{{- if and (.Values.cloudApi.enabled) (.Values.cloudApi.influxdb.enabled) -}}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
  name: influxdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
  selector: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
{{- end }}
