{{- if .Values.cloudApi.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus_metrics"
    prometheus.io/port: {{ default 5000 .Values.cloudApi.service.port | quote }}
    # Set up Dynatrace scraping
    metrics.dynatrace.com/scrape: "true"
    metrics.dynatrace.com/path: "/prometheus_metrics"
    metrics.dynatrace.com/port: {{ default 5000 .Values.cloudApi.service.port | quote }}
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cloud-api
  name: cloud-api
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ default "LoadBalancer" .Values.cloudApi.service.type }}
  ports:
    - name: "cloud-api"
      port: {{ default 5000 .Values.cloudApi.service.port }}
      targetPort: 5000
  selector: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cloud-api
{{- end }}
