apiVersion: v2
name: core-instance
description: Calyptia Core Instance chart
home: https://calyptia.com/products/core/
icon: https://storage.googleapis.com/calyptia_public_resources_bucket/logo-darkmode.svg
type: application
version: 0.0.8
appVersion: "v1.0.10"
maintainers:
  - name: Calyptia
    email: hello@calyptia.com
    url: www.calyptia.com
