name: "core-instance"
namespace: "core-operator"
clusterLogging: "false"
coreInstance: ""
coreSecret: "core-instance"
cloudToken: ""
cloudUrl: "https://cloud-api.calyptia.com"
fromcloudImage: "ghcr.io/calyptia/core-operator/sync-from-cloud:1.0.4"
tocloudImage: "ghcr.io/calyptia/core-operator/sync-to-cloud:1.0.4"
notls: "true"
interval: "15s"
serviceAccount: "controller-manager"
