name: "core-instance"
clusterLogging: "false"
coreInstance: ""
coreSecret: "core-instance"
cloudToken: ""
cloudUrl: "https://cloud-api.calyptia.com"
fromcloudImage: "ghcr.io/calyptia/core-operator/sync-from-cloud:v1.0.13"
tocloudImage: "ghcr.io/calyptia/core-operator/sync-to-cloud:v1.0.13"
notls: "true"
interval: "15s"
serviceAccount: "calyptia-core-controller-manager"
metricsPort: "15334"

annotations: {}
#   prometheus.io/path: "/api/v1/metrics/prometheus"
#   prometheus.io/port: "2020"
#   prometheus.io/scrape: "true"
