namespace:
## Namespace creation is set to false as the namespace is expected to be created through the CLI since eksctl command may require.
  create: false
  name: "calyptia-fluentbit"

## The service account creation configuration is taken care by the eksctl command to contact the AWS marketplace API's to fetch the image.
serviceAccount:
  create: false
## This is the name of the service account created by the eksctl create iamservice command.
  name: "<Enter the name of the service account>"
  annotations:
## This is the Role ARN of the IAM role which should have the required policy and trust relationship setup using OIDC.
    eks.amazonaws.com/role-arn: "<Enter the Role ARN of the IAM service account>"

image:
  repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/calyptia/calyptia-fb
  tag: 22.10.5
  pullPolicy: Always

imagePullSecrets:
### This is the Kubernetes secret created to authenticate to ECR. This should be created before installing this chart
  - name: "<Enter the name of the secret to pull the image>"

metricsPort: 2020
hostNetwork: false
dnsPolicy: ClusterFirst
livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http
extraVolumes: []
securityContext: {}
extraVolumeMounts: []

existingConfigMap: ""


service:
  type: ClusterIP
  annotations: {}

rbac:
  create: true
  nodeAccess: false

labels: {}
annotations:
  fluentbit.io/exclude: "true"

podAnnotations: {}

luaScripts: {}

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stdout
        Match *

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
  ## This configuration is deprecated, please use `extraFiles` instead.
  upstream: {}

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

  extraFiles: {}

# The config volume is mounted by default, either to the existingConfigMap value, or the default of "fluent-bit.fullname"
volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/fluent-bit.conf
    subPath: fluent-bit.conf
  - name: config
    mountPath: /fluent-bit/etc/custom_parsers.conf
    subPath: custom_parsers.conf

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true
