{{- if .Values.reloader.enabled -}}
---
# https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: reloader
  name: reloader
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ default 1 .Values.reloader.replicas }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: reloader
  {{- if .Values.reloader.updateStrategy }}
  strategy: {{- toYaml .Values.reloader.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
        {{- if .Values.reloader.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.reloader.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: reloader
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.reloader.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.frontend.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "reloader.imagePullSecrets" . | nindent 6 }}
      containers:
        - image: {{ template "reloader.image" . }}
          name: reloader
          ports:
            - name: http
              containerPort: 9090
          {{- if .Values.reloader.resources }}
          resources: {{- toYaml .Values.reloader.resources | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
          {{- if .Values.reloader.startupProbe }}
          startupProbe: {{- toYaml .Values.reloader.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.reloader.readinessProbe }}
          readinessProbe: {{- toYaml .Values.reloader.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.reloader.livenessProbe }}
          livenessProbe: {{- toYaml .Values.reloader.livenessProbe | nindent 12 }}
          {{- end }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          {{- if eq .Values.reloader.reloadOnCreate true }}
          - "--reload-on-create={{ .Values.reloader.reloadOnCreate }}"
          {{- end }}
          {{- if eq .Values.reloader.syncAfterRestart true }}
          - "--sync-after-restart={{ .Values.reloader.syncAfterRestart }}"
          {{- end }}
      restartPolicy: {{ default "Always" .Values.reloader.restartPolicy }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: {{ template "reloader.serviceAccountName" . }}
{{- end -}}
