# Turn this chart off/on
enabled: true
images:
  hotReload:
    registry: ghcr.io
    repository: calyptia/configmap-reload
    tag: 0.11.1
    pullSecrets: []
  fluentBit:
    registry: ghcr.io
    repository: calyptia/core/calyptia-fluent-bit
    tag: 24.10.1
    pullSecrets: []
  ingestCheck:
    registry: ghcr.io
    repository: calyptia/core/ingest-check
    tag: 0.0.7
    pullSecrets: []
cloudUrl: https://cloud-api.calyptia.com
pipelineServiceType: LoadBalancer
