## @section Common
## @descriptionStart
## Configures common parameters.
## @descriptionEnd
## @param enabled Enables this chart
enabled: true
## @param pipelineServiceType The default service type to use for a Pipeline if not explicitly set.
pipelineServiceType: LoadBalancer
## @section Images
## @descriptionStart
## Configures the default images used for Pipelines and Ingest Checks when not explicitly set at creation time.
## @descriptionEnd
images:
  hotReload:
    ## @param images.hotReload.registry Image registry.
    registry: ghcr.io
    ## @param images.hotReload.repository Image repository.
    repository: chronosphereio/configmap-reload
    ## @param images.hotReload.tag Image tag.
    tag: v1.0.0
  fluentBit:
    ## @param images.fluentBit.registry Image registry.
    registry: ghcr.io
    ## @param images.fluentBit.repository Image registry.
    repository: calyptia/core/calyptia-fluent-bit
    ## @param images.fluentBit.tag Image tag.
    tag: 25.9.3
  ingestCheck:
    ## @param images.ingestCheck.registry Image registry.
    registry: ghcr.io
    ## @param images.ingestCheck.repository Image repository.
    repository: calyptia/core/ingest-check
    ## @param images.ingestCheck.tag Image tag.
    tag: 0.0.7
