{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels:
  #  {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: operator
    calyptia.core: core-operator
    control-plane: controller-manager
  name: calyptia-core-controller-manager
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      calyptia.core: core-operator
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels:
      #  {{- include "common.labels.standard" . | nindent 8 }}
      #   {{- if .Values.commonLabels }}
      #   {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
      #   {{- end }}
      #   {{- if .Values.podLabels }}
      #   {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
      #   {{- end }}
        calyptia.core: core-operator
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
          image: {{ template "operator.image" . }}
          imagePullPolicy: {{ .Values.global.pullPolicy | quote }}
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe: {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          name: manager
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 8081
              name: http
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccount: {{ template "operator.serviceAccountName" . }}
      {{- include "operator.imagePullSecrets" . | nindent 6 }}
      terminationGracePeriodSeconds: 10
      volumes:
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      restartPolicy: {{ default "Always" .Values.restartPolicy }}

{{- end }}
