{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ default "regcreds" .Values.imageCredentials.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "createImagePullSecret" . }}
{{- end }}
