{{- if .Values.enabled }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    calyptia.core: core-operator
  name: calyptia-core-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calyptia-core-manager-role
subjects:
- kind: ServiceAccount
  name: {{ template "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    calyptia.core: core-operator
  name: calyptia-core-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calyptia-core-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ template "operator.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/created-by: core-operator
    app.kubernetes.io/managed-by: core-operator
    app.kubernetes.io/part-of: calyptia
    calyptia.core: core-operator
  name: calyptia-core-pod-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calyptia-core-pod-role
subjects:
- kind: ServiceAccount
  name: calyptia-core-po-sa
  namespace: {{ .Release.Namespace }}
{{- range .Values.serviceAccounts }}
- kind: ServiceAccount
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
  {{- end }}
{{- end -}}
{{- end }}
