{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "calyptia-fluent-bit.fullname" . }}
  labels:
    {{- include "calyptia-fluent-bit.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      {{- if .Values.rbac.nodeAccess }}
      - nodes
      - nodes/proxy
      {{- end }}
    verbs:
      - get
      - list
      - watch
  {{- if and .Values.openShift.enabled .Values.openShift.securityContextConstraints.create }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ include "calyptia-fluent-bit.fullname" . }}
    verbs:
      - use
  {{- end }}
{{- end -}}