{{- if gt (len .Values.luaScripts) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calyptia-fluent-bit.fullname" . }}-luascripts
  labels:
    {{- include "calyptia-fluent-bit.labels" . | nindent 4 }}
data:
  {{ range $key, $value := .Values.luaScripts }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
{{- end -}}
