apiVersion: v1
kind: Service
metadata:
  name: {{ include "calyptia-fluent-bit.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "calyptia-fluent-bit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.extraPorts }}
      {{- range .Values.extraPorts }}
      - name: {{ .name }}
        containerPort: {{ .containerPort }}
        protocol: {{ .protocol }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "calyptia-fluent-bit.selectorLabels" . | nindent 4 }}
