{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- printf "calyptia-core-instance-%s" .Release.Name | trunc 63 | trimSuffix "-" -}}"
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/instance: {{ .Values.coreInstance }}
    app.kubernetes.io/part-of: calyptia
    calyptia.core: core-instance
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/part-of: calyptia
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: from-cloud
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/part-of: calyptia
        calyptia.core: core-instance
    spec:
      serviceAccount: {{ template "instance.serviceAccountName" . }}
      containers:
      - env:
        - name: CORE_INSTANCE
          value: {{ required "coreInstance must be provided" .Values.coreInstance | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: CLOUD_URL
          value: {{ default "https://cloud-api.calyptia.com" .Values.cloudUrl | quote }}
        - name: TOKEN
          {{- if and .Values.cloudTokenSec.name .Values.cloudTokenSec.key }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.cloudTokenSec.name }}"
              key: "{{ .Values.cloudTokenSec.key }}"
          {{- else }}
          value: "{{ required "cloudToken must be provided" .Values.cloudToken }}"
          {{- end }}
        - name: INTERVAL
          value: {{ default "15s" .Values.interval | quote }}
        - name: CLUSTER_LOGGING
          value: {{ default false .Values.clusterLogging | quote }}
        - name: NO_TLS_VERIFY
          value: {{ default false .Values.notls | quote }}
        - name: HOTRELOAD_IMAGE
          value: {{ template "hotReload.image" . }}
        - name: ENABLE_HEALTH_CHECK_PIPELINE
          value: {{ .Values.enableHealthCheckPipeline | quote }}
        - name: HEALTH_CHECK_PIPELINE_PORT
          value: {{ .Values.healthCheckPipelinePort | quote }}
        - name: HEALTH_CHECK_PIPELINE_SERVICE_TYPE
          value: {{ .Values.healthCheckPipelineServiceType | quote }}
        - name: INGEST_CHECK_IMAGE
          value: {{ template "ingestCheck.image" . }}
        - name: ANNOTATIONS
          value: {{ .Values.calyptiaAnnotations }}
        - name: SKIP_SERVICE_CREATION
          value: {{ .Values.skipServiceCreation | quote }}
        - name: TOLERATIONS
          value: {{ .Values.calyptiaTolerations | quote }}
        - name: HTTP_PROXY
          value: {{ template "instance.httpProxy" . }}
        - name: HTTPS_PROXY
          value: {{ template "instance.httpsProxy" . }}
        - name: NO_PROXY
          value: {{ template "instance.noProxy" . }}
        - name: CLOUD_PROXY
          value: {{ template "instance.cloudProxy" . }}
        - name: DEBUG_PORT
          value: {{ .Values.fromCloud.debugPort | quote }}
        - name: CLOUD_TIMEOUT
          value: {{ .Values.cloudTimeout | quote }}
        image: {{ template "fromCloud.image" . }}
        imagePullPolicy: {{ .Values.global.pullpolicy | default .Values.images.fromCloud.pullPolicy | quote }}
        name: from-cloud
{{- if .Values.probeIntervalSec }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.fromCloud.debugPort }}
          initialDelaySeconds:  {{ .Values.probeIntervalSec }}
          periodSeconds: {{ .Values.probeIntervalSec }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.fromCloud.debugPort }}
          initialDelaySeconds:  {{ .Values.probeIntervalSec }}
          periodSeconds: {{ .Values.probeIntervalSec }}
{{- end }}
        {{- if .Values.fromCloud.resources }}
        resources: {{- toYaml .Values.fromCloud.resources | nindent 12 }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.fromCloud.debugPort }}
            name: debug
        volumeMounts:
        {{- if .Values.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.fromCloud.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.fromCloud.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
      - env:
        - name: CORE_INSTANCE
          value: {{ default .Release.Name .Values.coreInstance | quote }}
        - name: NAMESPACE
          value: {{ include "common.names.namespace" . | quote }}
        - name: CLOUD_URL
          value: {{ default "https://cloud-api.calyptia.com" .Values.cloudUrl | quote }}
        - name: TOKEN
          {{- if and .Values.cloudTokenSec.name .Values.cloudTokenSec.key }}
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.cloudTokenSec.name }}"
              key: "{{ .Values.cloudTokenSec.key }}"
          {{- else }}
          value: "{{ required "cloudToken must be provided" .Values.cloudToken }}"
          {{- end }}
        - name: INTERVAL
          value: {{ default "15s" .Values.interval | quote }}
        - name: NO_TLS_VERIFY
          value: {{ default false .Values.notls | quote }}
        - name: HTTP_PROXY
          value: {{ template "instance.httpProxy" . }}
        - name: HTTPS_PROXY
          value: {{ template "instance.httpsProxy" . }}
        - name: NO_PROXY
          value: {{ template "instance.noProxy" . }}
        - name: CLOUD_PROXY
          value: {{ template "instance.cloudProxy" . }}
{{/* metrics and metricsPort was the legacy way to set the toCloud port so it did not conflict with fromCloud */}}
{{- $toCloudPort := and .Values.metrics .Values.metricsPort | default .Values.toCloud.debugPort }}
        - name: DEBUG_PORT
          value: {{ $toCloudPort | quote }}
        - name: CLOUD_TIMEOUT
          value: {{ .Values.cloudTimeout | quote }}
        image: {{ template "toCloud.image" . }}
        imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.images.toCloud.pullPolicy | quote }}
        name: to-cloud
{{- if .Values.probeIntervalSec }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ $toCloudPort }}
          initialDelaySeconds:  {{ .Values.probeIntervalSec }}
          periodSeconds: {{ .Values.probeIntervalSec }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ $toCloudPort }}
          initialDelaySeconds:  {{ .Values.probeIntervalSec }}
          periodSeconds: {{ .Values.probeIntervalSec }}
{{- end }}
        {{- if .Values.toCloud.resources }}
        resources: {{- toYaml .Values.toCloud.resources | nindent 12 }}
        {{- end }}
        ports:
          - containerPort: {{ $toCloudPort }}
{{- if .Values.metrics }}
            name: metrics
{{- else }}
            name: debug
{{- end }}
        volumeMounts:
        {{- if .Values.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.toCloud.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.toCloud.extraVolumeMounts "context" $) | nindent 12 }}
        {{- end }}
    {{- if .Values.calyptiaTolerations }}
      tolerations:
      {{- $tolerations := .Values.calyptiaTolerations | split "," }}
      {{- range $toleration := $tolerations }}
        {{- $tolerationParts := split ":" $toleration }}
        {{- $keyValue := split "=" (index $tolerationParts._0) }}
        - key: "{{ $keyValue._0 }}"
          operator: "{{ $keyValue._1 }}"
          value: "{{ index $tolerationParts._1 }}"
          effect: "{{ index $tolerationParts._2 }}"
          {{- if gt (len $tolerationParts) 3 }}
          tolerationSeconds: {{ index $tolerationParts._3 }}
          {{- end }}
      {{- end }}
    {{- end }}
      volumes:
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      restartPolicy: {{ default "Always" .Values.restartPolicy }}
{{- end }}
