{{- if .Values.enabled }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    calyptia.core: core-operator
  name: "{{-  printf "calyptia-core-instance-%s-role" .Release.Name  -}}"
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - policy
  - core.calyptia.com
  - core
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - secrets
  - pods
  - pods/log
  - ingestchecks
  - ingestchecks/finalizers
  - ingestchecks/status
  - pipelines
  - pipelines/finalizers
  - pipelines/status
  verbs:
  - get
  - list
  - create
  - delete
  - patch
  - update
  - watch
  - deletecollection
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: operator
    calyptia.core: core-operator
  name: "{{-  printf "calyptia-core-instance-%s-rolebinding" .Release.Name  -}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{-  printf "calyptia-core-instance-%s-role" .Release.Name  -}}"
subjects:
- kind: ServiceAccount
  name: {{ template "instance.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}
{{- end }}
