{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "calyptia-fluent-bit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations | required "A valid .Values.serviceAccount.annotations required!" }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
