{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "calyptia-fluent-bit.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "calyptia-fluent-bit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
