{{ if .Values.monitoring.fluentBit }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  name: monitoring-daemonset
  namespace: {{ .Release.Namespace | quote }}
data:
    fluent-bit.conf: |-
        [SERVICE]
            Daemon              Off
            Flush               1
            Log_Level           info
            Parsers_File        /fluent-bit/etc/parsers.conf
            Parsers_File        /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server         On
            HTTP_Listen         0.0.0.0
            HTTP_Port           2020
            Health_Check        On
            Storage.Metrics     On

        [INPUT]
            Name                tail
            Path                /var/log/containers/*.log
            multiline.parser    docker, cri
            Tag                 kube.*
            Mem_Buf_Limit       5MB
            Skip_Long_Lines     On
            Skip_Empty_Lines    On
            # Ensure we do not tail our own logs otherwise it can snowball even with exclusion later
            Exclude_Path        /var/log/containers/*${POD_NAME}*.log
            Path_Key            filename

        [INPUT]
            Name                systemd
            Tag                 host.*
            Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail      On

        [INPUT]
            name                fluentbit_metrics
            tag                 metrics.calyptia
            scrape_on_start     true
            scrape_interval     30

        [INPUT]
            name                node_exporter_metrics
            tag                 metrics.node
            scrape_interval     30
            # Ensure these are mounted
            path.procfs         /host/proc
            path.sysfs          /host/sys

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On

        [OUTPUT]
            name                stdout
            match               *

        [OUTPUT]
            name                prometheus_exporter
            match               metrics.*
            host                0.0.0.0
            port                2021
            add_label           node ${NODE_NAME}

        # The following may not be present
        {{- if .Values.vivo.enabled }}
        [OUTPUT]
            name                forward
            host                vivo
            port                9000
            match               *
        {{- end }}
        {{- if .Values.monitoring.grafana }}
        [OUTPUT]
            name                loki
            match               *
            host                calyptia-cloud-loki
            auto_kubernetes_labels on

        [OUTPUT]
            name                prometheus_remote_write
            host                calyptia-cloud-prometheus-server
            match               *
            uri                 /api/v1/write
            add_label           job calyptia
            add_label           node ${NODE_NAME}
        {{- end }}
{{ end }}