name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  docslint-pr:
    runs-on: ubuntu-latest
    name: PR - Markdownlint
    steps:
      - name: Run markdownlint
        uses: actionshub/markdownlint@v3.1.4

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Add dependency charts
        run: |
          helm repo add fluent https://fluent.github.io/helm-charts --force-update
          helm repo add calyptia https://helm.calyptia.com --force-update
          helm repo add grafana https://grafana.github.io/helm-charts --force-update
          helm repo add prometheus https://prometheus-community.github.io/helm-charts --force-update
          helm repo update
        shell: bash

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.5.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --target-branch ${{ github.event.repository.default_branch }}
