name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  docslint-pr:
    runs-on: ubuntu-latest
    name: PR - Markdownlint
    steps:
      - name: Run markdownlint
        uses: actionshub/markdownlint@v3.1.3

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (list-changed)
        id: list-changed-core
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts/core,charts/fluentd)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
        
      - name: Run chart-testing (list-changed)
        id: list-changed-eks
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts/aws-fluent-bit,charts/aws-eks-addon)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
        
      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed-core.outputs.changed == 'true'

      - name: Run chart-testing (install) on KIND
        if: steps.list-changed-core.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts/core,charts/fluentd
        shell: bash

      - name: Create EKS cluster
        if: steps.list-changed-eks.outputs.changed == 'true'
        run: |
          eksctl create cluster --name "$CLUSTER_NAME"
          eksctl utils associate-iam-oidc-provider --cluster="$CLUSTER_NAME" --approve
          eksctl create iamserviceaccount \
            --name calyptia-fluentbit \
            --namespace calyptia-fluentbit \
            --cluster "$CLUSTER_NAME"\
            --attach-policy-arn arn:aws:iam::aws:policy/AWSMarketplaceMeteringRegisterUsage \
            --approve \
            --override-existing-serviceaccounts
        shell: bash
        env:
          CLUSTER_NAME: chart-testing
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run chart-testing (install) on EKS
        if: steps.list-changed-eks.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --chart-dirs charts/aws-fluent-bit,charts/aws-eks-addon
        shell: bash
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
