name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency charts
        run: |
          helm repo add fluent https://fluent.github.io/helm-charts --force-update
          helm repo add calyptia https://helm.calyptia.com --force-update
          helm repo add grafana https://grafana.github.io/helm-charts --force-update
          helm repo add prometheus https://prometheus-community.github.io/helm-charts --force-update
          helm repo update
        shell: bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
