name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency charts
        run: |
          helm repo add fluent https://fluent.github.io/helm-charts
        shell: bash

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true

  update-chart-yaml-template:
    name: Raise PR to update install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: none
    needs:
      - release
    steps:
      - name: Checkout repo with PAT supporting workflows
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}

      - run: |
          helm repo add calyptia http://helm.calyptia.com
          helm repo update
          helm template calyptia calyptia/core --set project_token='$PROJECT_TOKEN',core_instance_tags='$CORE_INSTANCE_TAGS',name='$CORE_INSTANCE_NAME' > install-core.yaml.tmpl
        shell: bash

      - name: Create PR for update
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'ci: update install-core.yaml template'
          signoff: true
          branch: ci_update_yaml_template
          delete-branch: true
          title: 'ci: update install-core.yaml template'
          token: ${{ secrets.CI_PAT }}
          labels: ci,automerge
          add-paths: |
            *yaml.tmpl
          body: |
            Update YAML
            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false
